<!-- Start Experience & Education section -->
<section class="ms-experience-section ms-slide  body-bg">
    <div class="container-fluid">
        <div class="row">
            <div class="section-title">
                <h2>ماذا <span>نقدم</span></h2>

            </div>
        </div>
        <div class="row">
            <h4 class="text-center">برامج متخصصة لتطوير جودة الحياة الوظيفية</h4>
        </div>
        <br /><br />

        <div class="row">
            <div class="col-lg-1"></div>
            <div class="col-lg-10 col-md-10 col-sm-12">
                <div class="text-center">

                    <!-- Image Map Generated by http://www.image-map.net/ -->
                    <img src="{{ asset('frontend/assets/img/services.png') }}" usemap="#image-map"
                        style="margin-bottom: 50px;" class="img-fluid">

                    <map name="image-map">
                        <area target="" alt="1" title="1" data-popup-open="popup-1" href="#"
                            coords="258,87,778,9" shape="rect">
                        <area target="" alt="2" title="2" data-popup-open="popup-2-0" href="#" coords="298,110,765,163"
                            shape="rect">
                        <area target="" alt="3" title="3" data-popup-open="popup-3-0" href="#" coords="771,263,354,196"
                            shape="rect">
                        <area target="" alt="4" title="4" data-popup-open="popup-4-0" href="#" coords="396,291,778,348"
                            shape="rect">
                    </map>
                </div>
            </div>




        </div>



    </div>
</section>
<!-- End Experience & Education Section -->
